quarkus.datasource.devservices.enabled=false
quarkus.http.cors.enabled=true
extractor.dpp.reference-ontology.vocabularies=http://dpp.taltech.ee/EUDPP#,http://dpp.taltech.ee/EUDPP
%dev.quarkus.http.cors.origins=/.*/
quarkus.http.auth.permission.capabilities.paths=/cababilities/v1*
quarkus.http.auth.permission.capabilities.policy=authenticated
quarkus.http.auth.permission.oapi.paths=/q/openapi
quarkus.http.auth.permission.oapi.policy=permit
