quarkus.datasource.devservices.enabled=false
quarkus.http.cors.enabled=true
extractor.dpp.reference-ontology.vocabularies=http://dpp.taltech.ee/EUDPP#,http://dpp.taltech.ee/EUDPP
%dev.quarkus.http.cors.origins=/.*/
%prod.quarkus.http.auth.permission.capabilities.paths=/cababilities/v1*
%prod.quarkus.http.auth.permission.capabilities.policy=authenticated
%prod.quarkus.http.auth.permission.oapi.paths=/q/openapi
%prod.quarkus.http.auth.permission.oapi.policy=permit
%prod.quarkus.http.auth.policy.config-policy.roles-allowed=admin,eu
%prod.quarkus.http.auth.permission.config.policy=config-policy
%prod.quarkus.http.auth.permission.config.paths=/config/v1*
