quarkus.datasource.db-kind=postgresql
quarkus.datasource.extraction.db-kind=postgresql
%dev.quarkus.datasource.extraction.username=postgres
%dev.quarkus.datasource.extraction.password=postgres
%dev.quarkus.datasource.extraction.reactive.url=vertx-reactive:postgresql://localhost:5432/cirpass
%dev.quarkus.datasource.username=postgres
%dev.quarkus.datasource.password=postgres
%dev.quarkus.datasource.reactive.url=vertx-reactive:postgresql://localhost:5432/cirpass